# Generated by Django 5.1.4 on 2025-01-07 19:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date(2025, 1, 7), verbose_name='Дата игры')),
                ('quantity', models.IntegerField(verbose_name='Количество игроков')),
                ('avg_score', models.FloatField(default='0', verbose_name='Средний счет за столом')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('score', models.FloatField(default='0', verbose_name='Рейтинг')),
                ('date_create', models.DateField(default=datetime.date(2025, 1, 7), verbose_name='Дата добавления')),
            ],
        ),
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(verbose_name='Занятое место')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Призовые')),
                ('score_gamer', models.FloatField(default='0', verbose_name='Очки игрока после игры')),
                ('game', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='stata.game', verbose_name='Игра')),
                ('person', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='stata.person', verbose_name='Игрок')),
            ],
        ),
    ]
